# Use the official PHP image with Apache server
FROM php:7.4-apache

# Copy the web application's files (HTML, CSS, PHP) to the Apache document root
COPY ./html /var/www/html

# Expose port 80 for the Apache server
EXPOSE 80
